export { default as Landing } from './Landing' 
export { default as GetStarted } from './GetStarted' 
export { default as Flavour } from './Flavour' 
export { default as HowItWorks } from './HowItWorks' 
export { default as Faqs } from './Faqs' 