export { default as Landing } from './Landing'
export { default as JobOffers } from './JobOffers'
export { default as NetPromoter } from './NetPromoter'
export { default as PartnerUs } from './PartnerUs'
export { default as EmployeePlan } from './EmployeePlan'
export { default as Team } from './Team'